# Generated by Django 4.1.1 on 2023-04-15 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=models.CharField(max_length=244), max_length=255)),
                ('course_title', models.CharField(max_length=244)),
                ('description', models.CharField(max_length=244)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, default=' ', null=True, upload_to='media/uploads/')),
                ('thumbnail', models.ImageField(blank=True, default=' ', null=True, upload_to='media/uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='course.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
